//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFile
    {
        public System.Guid FileID { get; set; }
        public Nullable<long> LineID { get; set; }
        public string FileName { get; set; }
        public string ContentType { get; set; }
        public string Name { get; set; }
    
        public virtual tblLine tblLine { get; set; }
    }
}
