//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblJob()
        {
            this.tblLines = new HashSet<tblLine>();
            this.tblJobFiles = new HashSet<tblJobFile>();
            this.tblEventStores = new HashSet<tblEventStore>();
        }
    
        public long JobID { get; set; }
        public Nullable<System.DateTime> QuoteDate { get; set; }
        public Nullable<long> ClientID { get; set; }
        public Nullable<long> ContactID { get; set; }
        public string CustomerRef { get; set; }
        public string Description { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Status { get; set; }
        public long NextLineID { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryDate { get; set; }
        public string OurOrderReference { get; set; }
    
        public virtual tblContact tblContact { get; set; }
        public virtual tblStatus tblStatus { get; set; }
        public virtual tblClient tblClient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLine> tblLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJobFile> tblJobFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEventStore> tblEventStores { get; set; }
    }
}
