//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseOrder
    {
        public long PurchaseOrderID { get; set; }
        public long LineID { get; set; }
        public string Description { get; set; }
        public decimal Cost { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> PurchaseOrderDate { get; set; }
        public long Quantity { get; set; }
        public string SupplierRef { get; set; }
    
        public virtual tblLine tblLine { get; set; }
    }
}
