//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTimesheet
    {
        public long TimesheetID { get; set; }
        public long LineID { get; set; }
        public System.Guid UserID { get; set; }
        public double Hours { get; set; }
        public string Comments { get; set; }
        public decimal HourlyRate { get; set; }
        public Nullable<System.DateTime> TimesheetDate { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblLine tblLine { get; set; }
    }
}
