//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUpload
    {
        public long UploadID { get; set; }
        public Nullable<System.Guid> DirectoryGUID { get; set; }
        public string UploadName { get; set; }
        public Nullable<long> UploadTypeID { get; set; }
    }
}
